"""empty message

Revision ID: 112dcdf89135
Revises: 9aac22b9cc0f
Create Date: 2023-03-08 17:38:55.697073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '112dcdf89135'
down_revision = '9aac22b9cc0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theatre_lists',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('procedure_time', sa.String(length=60), nullable=False),
    sa.Column('patient_name', sa.String(length=128), nullable=False),
    sa.Column('procedure_name', sa.String(length=128), nullable=False),
    sa.Column('surgeon', sa.String(length=128), nullable=False),
    sa.Column('anaesthetist', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('theatre_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theatre_lists_anaesthetist'), ['anaesthetist'], unique=False)
        batch_op.create_index(batch_op.f('ix_theatre_lists_patient_name'), ['patient_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_theatre_lists_procedure_name'), ['procedure_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_theatre_lists_procedure_time'), ['procedure_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_theatre_lists_surgeon'), ['surgeon'], unique=False)

    with op.batch_alter_table('theatre_ones', schema=None) as batch_op:
        batch_op.drop_index('ix_theatre_ones_anaesthetist')
        batch_op.drop_index('ix_theatre_ones_patient_name')
        batch_op.drop_index('ix_theatre_ones_procedure_name')
        batch_op.drop_index('ix_theatre_ones_procedure_time')
        batch_op.drop_index('ix_theatre_ones_surgeon')

    op.drop_table('theatre_ones')
    with op.batch_alter_table('surgeons', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('surgeons')
    op.drop_table('patient_booking')
    op.drop_table('theatre_surgeon')
    op.drop_table('procedures')
    op.drop_table('theatre_anaesthetist')
    op.drop_table('theatres')
    op.drop_table('patients')
    with op.batch_alter_table('anaesthetists', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('anaesthetists')
    op.drop_table('theatre_procedure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theatre_procedure',
    sa.Column('theatre_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('procedure_id', mysql.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], name='theatre_procedure_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatres.id'], name='theatre_procedure_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('theatre_id', 'procedure_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('anaesthetists',
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('contact_info', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('anaesthetists', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('patients',
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('contact_info', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('theatre_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatres.id'], name='patients_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('theatres',
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('theatre_anaesthetist',
    sa.Column('theatre_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('anaesthetist_id', mysql.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['anaesthetist_id'], ['anaesthetists.id'], name='theatre_anaesthetist_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatres.id'], name='theatre_anaesthetist_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('theatre_id', 'anaesthetist_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('procedures',
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('requirements', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('theatre_surgeon',
    sa.Column('theatre_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('surgeon_id', mysql.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeons.id'], name='theatre_surgeon_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatres.id'], name='theatre_surgeon_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('theatre_id', 'surgeon_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('patient_booking',
    sa.Column('patient_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('procedure_id', mysql.VARCHAR(length=60), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='patient_booking_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], name='patient_booking_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('surgeons',
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('contact_info', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('speciality', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('surgeons', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('theatre_ones',
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('procedure_time', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('patient_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('procedure_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('surgeon', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('anaesthetist', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('theatre_ones', schema=None) as batch_op:
        batch_op.create_index('ix_theatre_ones_surgeon', ['surgeon'], unique=False)
        batch_op.create_index('ix_theatre_ones_procedure_time', ['procedure_time'], unique=False)
        batch_op.create_index('ix_theatre_ones_procedure_name', ['procedure_name'], unique=False)
        batch_op.create_index('ix_theatre_ones_patient_name', ['patient_name'], unique=False)
        batch_op.create_index('ix_theatre_ones_anaesthetist', ['anaesthetist'], unique=False)

    with op.batch_alter_table('theatre_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theatre_lists_surgeon'))
        batch_op.drop_index(batch_op.f('ix_theatre_lists_procedure_time'))
        batch_op.drop_index(batch_op.f('ix_theatre_lists_procedure_name'))
        batch_op.drop_index(batch_op.f('ix_theatre_lists_patient_name'))
        batch_op.drop_index(batch_op.f('ix_theatre_lists_anaesthetist'))

    op.drop_table('theatre_lists')
    # ### end Alembic commands ###
